/**
 * scheduleme.server | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';
import { AccountsRemovePoolElementIdEmailUserFunctionPostIdParameter } from './accountsRemovePoolElementIdEmailUserFunctionPostIdParameter';


export interface RefreshToken { 
    refreshTokenId?: AccountsRemovePoolElementIdEmailUserFunctionPostIdParameter;
    account?: Account;
    token?: string | null;
    expires?: string;
    isExpired?: boolean;
    created?: string;
    createdByIp?: string | null;
    revoked?: string | null;
    revokedByIp?: string | null;
    replacedByToken?: string | null;
    isActive?: boolean;
}

