/**
 * scheduleme.server | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterRequest { 
    title: string | null;
    firstName: string | null;
    lastName: string | null;
    email: string | null;
    dob: string | null;
    password: string | null;
    confirmPassword: string | null;
    acceptTerms?: boolean;
}

