/**
 * scheduleme.server | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScheduleDateTime } from './scheduleDateTime';
import { AccountsRemovePoolElementIdEmailUserFunctionPostIdParameter } from './accountsRemovePoolElementIdEmailUserFunctionPostIdParameter';


export interface ScheduleDateTimeResponse { 
    id?: AccountsRemovePoolElementIdEmailUserFunctionPostIdParameter;
    scheduleDateTimes?: Array<ScheduleDateTime> | null;
}

