/**
 * scheduleme.server | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountsRemovePoolElementIdEmailUserFunctionPostIdParameter } from './accountsRemovePoolElementIdEmailUserFunctionPostIdParameter';
import { ScheduleNoOfTimesAssigned } from './scheduleNoOfTimesAssigned';


export interface Schedule { 
    scheduleId?: AccountsRemovePoolElementIdEmailUserFunctionPostIdParameter;
    date?: string | null;
    dob?: string | null;
    required?: boolean;
    email?: string | null;
    userAvailability?: boolean;
    userFunction?: string | null;
    scheduleGroup?: string | null;
    notifiedWeekBefore?: boolean;
    notifiedThreeDaysBefore?: boolean;
    noOfTimesAssigned?: ScheduleNoOfTimesAssigned;
    noOfTimesDropped?: ScheduleNoOfTimesAssigned;
}

