/**
 * scheduleme.server | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountsRemovePoolElementIdEmailUserFunctionPostIdParameter } from './accountsRemovePoolElementIdEmailUserFunctionPostIdParameter';


export interface SchedulePoolElement { 
    id?: AccountsRemovePoolElementIdEmailUserFunctionPostIdParameter;
    email?: string | null;
    date?: string | null;
    required?: boolean;
    userAvailability?: boolean;
    userFunction?: string | null;
    scheduleGroup?: string | null;
}

