/**
 * scheduleme.server | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountsRemovePoolElementIdEmailUserFunctionPostIdParameter } from './accountsRemovePoolElementIdEmailUserFunctionPostIdParameter';


export interface TimeSlotTasks { 
    timeSlotTasksId?: AccountsRemovePoolElementIdEmailUserFunctionPostIdParameter;
    date?: string | null;
    tasks?: string | null;
}

