/**
 * scheduleme.server | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateScheduleRequest { 
    accountId?: string | null;
    date?: string | null;
    dob?: string | null;
    email?: string | null;
    newDate?: string | null;
    required: boolean;
    userAvailability?: boolean;
    userFunction?: string | null;
    newUserFunction?: string | null;
    scheduleGroup?: string | null;
}

