name: JD Real Test
on:
  push:

env:
  MY_FAVORITE_NO: 2

jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Greetings
        run: echo "Hello"

        - name: Print secrets
        run: echo "Hello"
        run: echo Kestrel__Endpoints__Https__Url
        run: echo Kestrel__Endpoints__Https__Certificate__Path
        run: echo Kestrel__Endpoints__Https__Certificate__Password
        run: echo AppSettings__SpryngApiToken
        run: echo AppSettings__SmtpPass
        run: echo AppSettings__JwtSecret
        run: echo AppSettings__BrevoApiKey
