name: JD Real Test
on:
  workflow_dispatch:

env:
  MY_FAVORITE_NO: 2

jobs:
  deployment: My fiest Job
    runs-on: windows-latest
    environment:
      name: production
      url: https://github.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Greetings
        run: echo "Hello"

      - name: Print secrets
        run: |
          echo "APP_SECRET: ${{secrets.APP_SECRET}}"
          echo "Kestrel__Endpoints__Https__Url: ${{secrets.Kestrel__Endpoints__Https__Url}}"
          echo "Kestrel__Endpoints__Https__Certificate__Path: ${{secrets.Kestrel__Endpoints__Https__Certificate__Path}}"
          echo "Kestrel__Endpoints__Https__Certificate__Password: ${{secrets.Kestrel__Endpoints__Https__Certificate__Password}}"
          echo "AppSettings__SpryngApiToken: ${{secrets.AppSettings__SpryngApiToken}}"
          echo "AppSettings__SmtpPass: ${{secrets.AppSettings__SmtpPass}}"
          echo "AppSettings__JwtSecret: ${{secrets.AppSettings__JwtSecret}}"
          echo "AppSettings__BrevoApiKey: ${{secrets.AppSettings__BrevoApiKey}}"

      - name: Print secrets as environment variables
        #run: |
        #  echo "Kestrel__Endpoints__Https__Url: $Kestrel__Endpoints__Https__Url"
        env:
          Kestrel__Endpoints__Https__Url: ${{secrets.Kestrel__Endpoints__Https__Url}}
        run: |
          echo "Kestrel__Endpoints__Https__Url: $Kestrel__Endpoints__Https__Url"
