/**
 * scheduleme.server | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RefreshToken } from './refreshToken';
import { AgentTask } from './agentTask';
import { Schedule } from './schedule';
import { AccountsRemovePoolElementIdEmailUserFunctionPostIdParameter } from './accountsRemovePoolElementIdEmailUserFunctionPostIdParameter';


export interface Account { 
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    acceptTerms?: boolean;
    role?: number;
    verificationToken?: string | null;
    verified?: string | null;
    isVerified?: boolean;
    resetToken?: string | null;
    resetTokenExpires?: string | null;
    passwordReset?: string | null;
    dob?: string | null;
    created?: string;
    updated?: string | null;
    notifyWeekBefore?: boolean;
    notifyThreeDaysBefore?: boolean;
    mfaEnabled?: boolean;
    schedules?: Array<Schedule> | null;
    userFunctions?: Array<AgentTask> | null;
    refreshTokens?: Array<RefreshToken> | null;
    id?: string | null;
    userName?: string | null;
    normalizedUserName?: string | null;
    email?: string | null;
    normalizedEmail?: string | null;
    emailConfirmed?: boolean;
    passwordHash?: string | null;
    securityStamp?: string | null;
    concurrencyStamp?: string | null;
    phoneNumber?: string | null;
    phoneNumberConfirmed?: boolean;
    twoFactorEnabled?: boolean;
    lockoutEnd?: string | null;
    lockoutEnabled?: boolean;
    accessFailedCount?: AccountsRemovePoolElementIdEmailUserFunctionPostIdParameter;
}

