/**
 * scheduleme.server | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgentTask } from './agentTask';
import { Schedule } from './schedule';


export interface AccountResponse { 
    id?: string | null;
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    phoneNumber?: string | null;
    scheduleGroup?: string | null;
    dob: string | null;
    role?: string | null;
    created?: string;
    updated?: string | null;
    isVerified?: boolean;
    schedules?: Array<Schedule> | null;
    userFunctions?: Array<AgentTask> | null;
}

