/**
 * scheduleme.server | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgentTaskFunctionId } from './agentTaskFunctionId';


export interface AgentTask { 
    functionId?: AgentTaskFunctionId;
    preferredTime?: string | null;
    userFunction?: string | null;
    group?: string | null;
    isGroup?: boolean;
}

