/**
 * scheduleme.server | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { AccountsRemovePoolElementIdEmailUserFunctionPostIdParameter } from './accountsRemovePoolElementIdEmailUserFunctionPostIdParameter';


export interface DateFunctionTeam { 
    id?: AccountsRemovePoolElementIdEmailUserFunctionPostIdParameter;
    userFunction?: string | null;
    users?: Array<User> | null;
}

