/**
 * scheduleme.server | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DateFunctionTeam } from './dateFunctionTeam';
import { AccountsRemovePoolElementIdEmailUserFunctionPostIdParameter } from './accountsRemovePoolElementIdEmailUserFunctionPostIdParameter';


export interface DateFunctionTeamResponse { 
    id?: AccountsRemovePoolElementIdEmailUserFunctionPostIdParameter;
    dateFunctionTeams?: Array<DateFunctionTeam> | null;
}

