/**
 * scheduleme.server | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgentTask } from './agentTask';


export interface UpdateUserFunctionRequest { 
    userFunction: AgentTask;
}

