/**
 * scheduleme.server | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    id?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    'function'?: string | null;
    date?: string;
    userAvailability?: boolean;
    scheduleGroup?: string | null;
    dob?: string | null;
}

